export const CLIENTES_LABELS = {
  titulo: 'Clientes',
  agregar: 'Agregar cliente',
  editar: 'Editar cliente',
  eliminar: 'Eliminar cliente',
  nombre: 'Nombre',
  cedula: 'Cédula',
  cedulaOpcional: 'Cédula (opcional)',
  cedulaAyuda: 'Déjala vacía si el cliente es menor de edad; puedes agregarla después.',
  sinCedula: 'Sin cédula',
  conCedula: 'Con cédula',
  cedulaTodas: 'Cédula: todas',
  telefono: 'Teléfono',
  fechaInicio: 'Fecha de inicio',
  observaciones: 'Observaciones',
  estado: 'Estado',
  acciones: 'Acciones',
  activo: 'Activo',
  inactivo: 'Inactivo',
  buscar: 'Buscar por nombre o cédula...',
  filtrarEstado: 'Filtrar por estado',
  todos: 'Todos',
  sinClientes: 'No se encontraron clientes.',
  telefonoPlaceholder: 'XXXX-XXXX',
  cedulaPlaceholder: 'X-XXXX-XXXX',
  observacionesPlaceholder: 'Observaciones adicionales...',
  filtrarFechaDesde: 'Desde',
  filtrarFechaHasta: 'Hasta',
  historial: 'Historial de facturas',
  verHistorial: 'Historial',
  sinFacturas: 'Este cliente no tiene facturas registradas.',
} as const

export const CLIENTES_MESSAGES = {
  confirmarEliminar: '¿Estás seguro de que deseas eliminar a',
  accionIrreversible: 'Esta acción no se puede deshacer.',
  creado: 'Cliente creado exitosamente',
  actualizado: 'Cliente actualizado exitosamente',
  eliminado: 'Cliente eliminado exitosamente',
  errorCrear: 'Error al crear cliente',
  errorActualizar: 'Error al actualizar cliente',
  errorEliminar: 'Error al eliminar cliente',
  guardando: 'Guardando...',
  guardar: 'Guardar',
  cancelar: 'Cancelar',
  editarBtn: 'Editar',
  eliminarBtn: 'Eliminar',
  historialBtn: 'Historial',
  buscarBtn: 'Buscar',
  limpiarFiltrosBtn: 'Limpiar filtros',
} as const
