export const ESTADISTICAS_LABELS = {
  titulo: 'Estadísticas',
  totalClientes: 'Total clientes',
  clientesActivos: 'Clientes activos',
  clientesInactivos: 'Clientes inactivos',
  tasaCancelacion: 'Tasa de cancelación',
  totalFacturas: 'Total facturas',
  totalGanancias: 'Ganancias totales',
  clientesPorMes: 'Clientes nuevos por mes',
  paquetesVendidos: 'Paquetes más vendidos (Top 5)',
  gananciasPorMes: 'Ganancias por mes',
  comparativa: 'Comparativa de ganancias',
  desde: 'Desde',
  hasta: 'Hasta',
  filtrar: 'Filtrar',
  sinDatos: 'Sin datos para mostrar',
  cantidad: 'Cantidad',
  ventas: 'Ventas',
  ganancias: 'Ganancias',
  cargando: 'Cargando estadísticas...',
} as const
