export const FACTURAS_LABELS = {
  titulo: 'Facturas',
  agregar: 'Nueva factura',
  editar: 'Editar factura',
  eliminar: 'Eliminar factura',
  cliente: 'Cliente',
  cedula: 'Cédula del cliente',
  cedulaPlaceholder: 'X-XXXX-XXXX',
  clienteNoEncontrado: 'Cliente no encontrado',
  paquete: 'Paquete',
  categoria: 'Categoría',
  precioBase: 'Precio base',
  descuento: 'Descuento',
  descuentoTipo: 'Tipo',
  descuentoTipoPorcentaje: 'Porcentaje (%)',
  descuentoTipoMonto: 'Monto fijo',
  descuentoTotal: 'Descuento total',
  monto: 'Monto final',
  totalCliente: 'Total que paga el cliente',
  comision: 'Comisión del canal',
  comisionTipo: 'Tipo',
  comisionValor: 'Valor',
  comisionAyuda: 'Se calcula sobre lo que paga el cliente y no reduce su total: solo reduce el neto.',
  origen: 'Origen de la reserva',
  origenPlaceholder: 'Booking, Directo, agencia...',
  montoNeto: 'Neto para el negocio',
  precioAbiertoAyuda: 'Paquete de precio abierto: indique el precio de esta factura.',
  precioReferencia: 'Precio de referencia del paquete',
  fechaFacturacion: 'Fecha de facturación',
  fechaProximoPago: 'Próximo pago',
  pagoUnico: 'Pago único',
  pagoUnicoAyuda: 'Los paquetes de precio abierto se cobran una sola vez: no generan próximo pago.',
  usuario: 'Registrado por',
  acciones: 'Acciones',
  todas: 'Todas',
  todasCategorias: 'Todas las categorías',
  todosPaquetes: 'Todos los paquetes',
  buscarCliente: 'Buscar por nombre o cédula...',
  filtrarFecha: 'Filtrar por fecha de pago',
  sinFacturas: 'No se encontraron facturas.',
  seleccionarCategoria: 'Seleccionar categoría',
  seleccionarPaquete: 'Seleccionar paquete',
  sinPaquetesCategoria: 'No hay paquetes disponibles para esta categoría',
  montoAutoCalculado: 'Auto-calculado por paquete, editable',
  fechaAutoCalculada: 'Auto-calculada por duración, editable',
} as const

export const FACTURAS_MESSAGES = {
  confirmarEliminar: '¿Estás seguro de que deseas eliminar esta factura de',
  accionIrreversible: 'Esta acción no se puede deshacer.',
  guardando: 'Guardando...',
  guardar: 'Guardar',
  cancelar: 'Cancelar',
  editarBtn: 'Editar',
  eliminarBtn: 'Eliminar',
} as const
