export const FACTURAS_LABELS = {
  titulo: 'Facturas',
  agregar: 'Nueva factura',
  editar: 'Editar factura',
  eliminar: 'Eliminar factura',
  cliente: 'Cliente',
  cedula: 'Cédula del cliente',
  cedulaPlaceholder: 'X-XXXX-XXXX',
  clienteNoEncontrado: 'Cliente no encontrado',
  paquete: 'Paquete',
  categoria: 'Categoría',
  precioBase: 'Precio base',
  deduccionPaquete: 'Deducción del paquete',
  descuento: 'Descuento adicional',
  descuentoTipo: 'Tipo',
  descuentoTipoPorcentaje: 'Porcentaje (%)',
  descuentoTipoMonto: 'Monto fijo',
  descuentoTotal: 'Descuento total',
  monto: 'Monto final',
  fechaFacturacion: 'Fecha de facturación',
  fechaProximoPago: 'Próximo pago',
  usuario: 'Registrado por',
  acciones: 'Acciones',
  todas: 'Todas',
  todasCategorias: 'Todas las categorías',
  todosPaquetes: 'Todos los paquetes',
  buscarCliente: 'Buscar por nombre o cédula...',
  filtrarFecha: 'Filtrar por fecha de pago',
  sinFacturas: 'No se encontraron facturas.',
  seleccionarCategoria: 'Seleccionar categoría',
  seleccionarPaquete: 'Seleccionar paquete',
  sinPaquetesCategoria: 'No hay paquetes disponibles para esta categoría',
  montoAutoCalculado: 'Auto-calculado por paquete, editable',
  fechaAutoCalculada: 'Auto-calculada por duración, editable',
} as const

export const FACTURAS_MESSAGES = {
  confirmarEliminar: '¿Estás seguro de que deseas eliminar esta factura de',
  accionIrreversible: 'Esta acción no se puede deshacer.',
  guardando: 'Guardando...',
  guardar: 'Guardar',
  cancelar: 'Cancelar',
  editarBtn: 'Editar',
  eliminarBtn: 'Eliminar',
} as const
