export const PAQUETES_LABELS = {
  titulo: 'Paquetes',
  tabPaquetes: 'Paquetes',
  tabCategorias: 'Categorías',
  agregar: 'Agregar paquete',
  editar: 'Editar paquete',
  eliminar: 'Eliminar paquete',
  nombre: 'Nombre',
  precio: 'Precio',
  precioReferencia: 'Precio de referencia (opcional)',
  modoPrecio: 'Modo de precio',
  precioFijo: 'Precio fijo',
  precioFijoAyuda: 'El precio del paquete se usa tal cual al facturar.',
  precioAbierto: 'Precio abierto',
  precioAbiertoAyuda: 'El precio se ajusta en cada factura. El de aquí solo sirve de referencia.',
  precioAbiertoBadge: 'Abierto',
  porNoche: 'Por noche (hotel)',
  porNocheAyuda: 'El total se calcula al facturar: tarifa por noche × cantidad de noches. Es un cobro único, sin próximo pago.',
  porNocheBadge: 'Por noche',
  tarifaNoche: 'Tarifa por noche (opcional)',
  sufijoNoche: '/noche',
  sinPrecio: 'A convenir',
  categoria: 'Categoría',
  duracion: 'Duración (días)',
  estado: 'Estado',
  acciones: 'Acciones',
  activo: 'Activo',
  inactivo: 'Inactivo',
  todos: 'Todos',
  todasCategorias: 'Todas las categorías',
  buscar: 'Buscar por nombre...',
  filtrarEstado: 'Estado',
  filtrarCategoria: 'Categoría',
  sinPaquetes: 'No se encontraron paquetes.',
  seleccionarCategoria: 'Seleccionar categoría',
} as const

export const PAQUETES_MESSAGES = {
  cambioModoPrecio: 'Las facturas ya emitidas conservan el precio con que se generaron.',
  precioRequerido: 'El precio es requerido en un paquete de precio fijo',
  confirmarEliminar: '¿Estás seguro de que deseas eliminar el paquete',
  accionIrreversible: 'Esta acción no se puede deshacer.',
  errorConFacturas: 'No se puede eliminar un paquete asociado a facturas.',
  errorCrear: 'Error al crear paquete',
  errorActualizar: 'Error al actualizar paquete',
  guardando: 'Guardando...',
  guardar: 'Guardar',
  cancelar: 'Cancelar',
  editarBtn: 'Editar',
  eliminarBtn: 'Eliminar',
} as const
