export const PAQUETES_LABELS = {
  titulo: 'Paquetes',
  tabPaquetes: 'Paquetes',
  tabCategorias: 'Categorías',
  agregar: 'Agregar paquete',
  editar: 'Editar paquete',
  eliminar: 'Eliminar paquete',
  nombre: 'Nombre',
  precio: 'Precio',
  categoria: 'Categoría',
  duracion: 'Duración',
  duracionUnidad: 'Unidad',
  unidadDias: 'Días',
  unidadMeses: 'Meses',
  deduccion: 'Deducción',
  descuentoTipo: 'Tipo de deducción',
  descuentoValor: 'Valor de deducción',
  descuentoTipoPorcentaje: 'Porcentaje (%)',
  descuentoTipoMonto: 'Monto fijo',
  descuentoAyuda: 'Se aplica automáticamente al facturar este paquete. 0 = sin deducción.',
  sinDescuento: '—',
  estado: 'Estado',
  acciones: 'Acciones',
  activo: 'Activo',
  inactivo: 'Inactivo',
  todos: 'Todos',
  todasCategorias: 'Todas las categorías',
  buscar: 'Buscar por nombre...',
  filtrarEstado: 'Estado',
  filtrarCategoria: 'Categoría',
  sinPaquetes: 'No se encontraron paquetes.',
  seleccionarCategoria: 'Seleccionar categoría',
} as const

export const PAQUETES_MESSAGES = {
  confirmarEliminar: '¿Estás seguro de que deseas eliminar el paquete',
  accionIrreversible: 'Esta acción no se puede deshacer.',
  errorConFacturas: 'No se puede eliminar un paquete asociado a facturas.',
  errorCrear: 'Error al crear paquete',
  errorActualizar: 'Error al actualizar paquete',
  guardando: 'Guardando...',
  guardar: 'Guardar',
  cancelar: 'Cancelar',
  editarBtn: 'Editar',
  eliminarBtn: 'Eliminar',
} as const
